version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:19.7.0

jobs:
  buildAndDeploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$npm_TOKEN
            npm publish

workflows:
  main:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
